### ISSUE TITLE
Failed to load API Definition

### ISSUE THREAD

**Issue by nickjtch** [sacconazzo/directus-extension-api-docs#3]
![image](https://user-images.githubusercontent.com/9370214/209952907-d0421f26-2749-4b26-8c08-bfcf7a1e86b2.png)

### Steps

1. Installed the extension in the directus local directory
2. Made sure I am able to read `/server/specs/oas` in browser (by enabling the right permissions in Directus settings)

Any ideas?

**Comment by DeltaCorporate** [comment]
i have the same issue is there any solution for this?

**Comment by sacconazzo** [comment]
Hi @nickjtch @DeltaCorporate thank you for sharing issue.
Could you provide some more info?
The version of Directus? Is there any configuration specified in oasconfig.yaml or oas.yaml?

**Comment by nickjtch** [comment]
@sacconazzo 

Version: Directus 9.22.1
No configuration added since the docs indicate that they are optional.

**Comment by sacconazzo** [comment]
@nickjtch could you try if the error still occurs with the newly released `1.4.5`?

If so, could you please share the error message in the logs on call `/api-docs/oas`?
<img width="486" alt="image" src="https://user-images.githubusercontent.com/32107095/210015592-2837253b-e4a1-4c92-baae-80c99703e981.png">


Any suggestions, including improvements to the code, are welcome. 😎 Would be great.

Thank You

**Comment by nickjtch** [comment]
@sacconazzo works perfectly now with `1.4.5`. Thank you!
