### ISSUE TITLE
Hide some informations

### ISSUE THREAD

**Issue by paulofaia** [sacconazzo/directus-extension-api-docs#6]
Hi, i need hidden some information in api-docs.. 
How it's works? i not found any doc about this.. 
can u help me? Thanks :)

**Comment by sacconazzo** [comment]
Hi @paulofaia,
thank you for your feedback.

It's something I had in mind to do:
- insert a new parameter in the `oasconfig.yaml` file that allows you to specify some `tags` or `endpoints` to exclude in the generated oas file & consequently in swagger intarface. It might be useful.

Maybe you were referring to something like this, right?

Giona

**Comment by paulofaia** [comment]
Hey @sacconazzo ! 
Thanks for the answer :)

Yes! I imagined something like that, maybe a parameter with the collections I want to display in the swagger. (not exclusion)

What do you think about it?

**Comment by sacconazzo** [comment]
> Hey @sacconazzo ! 
> 
> Thanks for the answer :)
> 
> 
> 
> Yes! I imagined something like that, maybe a parameter with the collections I want to display in the swagger. (not exclusion)
> 
> 
> 
> What do you think about it?

I think it is a good idea.. 

New array parameter like **publishedTags**

I'm working on it.

I'll let you know soon

**Comment by sacconazzo** [comment]
Hi @paulofaia

from version [`1.6`](https://www.npmjs.com/package/directus-extension-api-docs/v/1.6.0) you should have this new array parameter:
- `publishedTags`

Let me know. :)

Giona

**Comment by paulofaia** [comment]
WOWWWW amazingg! 
I'll try here... 
Thanks Giona
